version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  database:
    image: postgres:14.7
    container_name: cards_service_db
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_DB: cards_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-cards-service:/var/lib/postgresql/data
    networks:
      - fighters-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafkaDBF
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  # ✅ Добавлено
      - KAFKA_KRAFT_CLUSTER_ID=abcdefgh12345678
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

volumes:
  postgres-cards-service:
    name: postgres-cards-service

networks:
  fighters-network:
    name: fighters-network

