server:
    port: 8082

spring:
    application:
        name: user-service
    #  profiles:
    #    active: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5434/cards_service_db
        username: postgres
        password: postgres

    liquibase:
        change-log: db/changelog/liquibase-master.yml

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            group-id: my-group
            auto-offset-reset: earliest