server:
    port: 8082

spring:
    application:
        name: user-service
    #  profiles:
    #    active: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5434/cards_service_db
        username: postgres
        password: postgres

    liquibase:
        change-log: db/changelog/liquibase-master.yml